<?php

/**
 * This is the model base class for the table "padre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Padre".
 *
 * Columns in table "padre" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $Nombres
 * @property string $Apellidos
 * @property string $fecha_nacimiento
 *
 */
abstract class BasePadre extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'padre';
    }

    public static function representingColumn() {
        return 'Nombres';
    }

    public function rules() {
        return array(
            array('Nombres, Apellidos', 'required'),
            array('Nombres, Apellidos', 'length', 'max'=>60),
            array('fecha_nacimiento', 'safe'),
            array('fecha_nacimiento', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, Nombres, Apellidos, fecha_nacimiento', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'Nombres' => Yii::t('app', 'Nombres'),
                'Apellidos' => Yii::t('app', 'Apellidos'),
                'fecha_nacimiento' => Yii::t('app', 'Fecha Nacimiento'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('Nombres', $this->Nombres, true);
        $criteria->compare('Apellidos', $this->Apellidos, true);
        $criteria->compare('fecha_nacimiento', $this->fecha_nacimiento, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}