<?php

/**
 * This is the model base class for the table "confirmacion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Confirmacion".
 *
 * Columns in table "confirmacion" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $persona_id
 * @property string $fecha_confirmacion
 * @property string $iglesia
 * @property integer $padre_parroquia_id
 * @property integer $papa_id
 * @property integer $mama_id
 * @property string $feligreses_de
 * @property integer $padrino_id
 * @property integer $madrina_id
 * @property integer $tomo_id
 * @property integer $pagina
 * @property integer $numero
 * @property string $nota
 * @property string $ano_bautizo
 * @property integer $tomo_bautizo
 * @property integer $pagina_bautizo
 * @property integer $numero_bautizo
 * @property string $lugar_bautizo
 * @property string $fecha_bautizo
 *
 */
abstract class BaseConfirmacion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'confirmacion';
    }

    public static function representingColumn() {
        return 'fecha_confirmacion';
    }

    public function rules() {
        return array(
            array('persona_id, fecha_confirmacion, padre_parroquia_id, tomo_id, pagina, numero', 'required'),
            array('persona_id, padre_parroquia_id, papa_id, mama_id, padrino_id, madrina_id, tomo_id, pagina, numero, tomo_bautizo, pagina_bautizo, numero_bautizo', 'numerical', 'integerOnly'=>true),
            array('iglesia', 'length', 'max'=>60),
            array('feligreses_de', 'length', 'max'=>64),
            array('nota', 'length', 'max'=>150),
            array('ano_bautizo', 'length', 'max'=>4),
            array('lugar_bautizo', 'length', 'max'=>40),
            array('fecha_bautizo', 'safe'),
            array('iglesia, papa_id, mama_id, feligreses_de, padrino_id, madrina_id, nota, ano_bautizo, tomo_bautizo, pagina_bautizo, numero_bautizo, lugar_bautizo, fecha_bautizo', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, persona_id, fecha_confirmacion, iglesia, padre_parroquia_id, papa_id, mama_id, feligreses_de, padrino_id, madrina_id, tomo_id, pagina, numero, nota, ano_bautizo, tomo_bautizo, pagina_bautizo, numero_bautizo, lugar_bautizo, fecha_bautizo', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'persona_id' => Yii::t('app', 'Persona'),
                'fecha_confirmacion' => Yii::t('app', 'Fecha Confirmacion'),
                'iglesia' => Yii::t('app', 'Iglesia'),
                'padre_parroquia_id' => Yii::t('app', 'Padre Parroquia'),
                'papa_id' => Yii::t('app', 'Papa'),
                'mama_id' => Yii::t('app', 'Mama'),
                'feligreses_de' => Yii::t('app', 'Feligreses De'),
                'padrino_id' => Yii::t('app', 'Padrino'),
                'madrina_id' => Yii::t('app', 'Madrina'),
                'tomo_id' => Yii::t('app', 'Tomo'),
                'pagina' => Yii::t('app', 'Pagina'),
                'numero' => Yii::t('app', 'Numero'),
                'nota' => Yii::t('app', 'Nota'),
                'ano_bautizo' => Yii::t('app', 'Ano Bautizo'),
                'tomo_bautizo' => Yii::t('app', 'Tomo Bautizo'),
                'pagina_bautizo' => Yii::t('app', 'Pagina Bautizo'),
                'numero_bautizo' => Yii::t('app', 'Numero Bautizo'),
                'lugar_bautizo' => Yii::t('app', 'Lugar Bautizo'),
                'fecha_bautizo' => Yii::t('app', 'Fecha Bautizo'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('persona_id', $this->persona_id);
        $criteria->compare('fecha_confirmacion', $this->fecha_confirmacion, true);
        $criteria->compare('iglesia', $this->iglesia, true);
        $criteria->compare('padre_parroquia_id', $this->padre_parroquia_id);
        $criteria->compare('papa_id', $this->papa_id);
        $criteria->compare('mama_id', $this->mama_id);
        $criteria->compare('feligreses_de', $this->feligreses_de, true);
        $criteria->compare('padrino_id', $this->padrino_id);
        $criteria->compare('madrina_id', $this->madrina_id);
        $criteria->compare('tomo_id', $this->tomo_id);
        $criteria->compare('pagina', $this->pagina);
        $criteria->compare('numero', $this->numero);
        $criteria->compare('nota', $this->nota, true);
        $criteria->compare('ano_bautizo', $this->ano_bautizo, true);
        $criteria->compare('tomo_bautizo', $this->tomo_bautizo);
        $criteria->compare('pagina_bautizo', $this->pagina_bautizo);
        $criteria->compare('numero_bautizo', $this->numero_bautizo);
        $criteria->compare('lugar_bautizo', $this->lugar_bautizo, true);
        $criteria->compare('fecha_bautizo', $this->fecha_bautizo, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}